global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot-admin"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "172.19.0.2:8080" ]
    basic_auth:
      username: 'admin'
      password: 'admin'

  - job_name: "product_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "172.19.0.3:2020" ]
    basic_auth:
      username: 'admin'
      password: 'admin'


  - job_name: "order_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "172.19.0.5:4040" ]
    basic_auth:
      username: 'admin'
      password: 'admin'